### ISSUE TITLE
Update to keycloak 12

### ISSUE THREAD

**Issue by dnlkoch** [terrestris/shogun-docker#7]
Keycloak 12 is available via `jboss/keycloak:12.0.2`. 

This should be updated and tested.

**Comment by ahennr** [comment]
I've successfully tested the upgrade of keycloak to v12.0.4 (from 11.0.0) in a customer project. As stated in the [Release notes](https://www.keycloak.org/2020/12/keycloak-1200-released.html) of v12, login theme was updated to PatternFly 4 which requires changes in (login) themes. For `shogun-docker`, however, this might be irrelevant.
